### ISSUE TITLE
port improvements to zeopp-lsmo fork?

### ISSUE THREAD

**Issue by ltalirz** [Luthaf/zeopp#1]
hi @Luthaf - just noticed that you also have your own zeo++ fork ;-)

we have one from the lsmo that includes a few fixes https://github.com/lsmo-epfl/zeopp-lsmo and also has an accompagnying package on conda-forge https://anaconda.org/conda-forge/zeopp-lsmo 

I was wondering whether you added any improvements that we should also incorporate?
e.g. I'm wondering about your commit to fix parsing of cssr files d3fed24fb157583323ece4966f98df293d3fa9a4 , but browsing through it I only see whitespace changes  (?)

**Comment by Luthaf** [comment]
Hi there! 

The main change for CSSR file is here, a bit hidden in the whitespace noise: https://github.com/Luthaf/zeopp/commit/d3fed24fb157583323ece4966f98df293d3fa9a4#diff-51889dcdc67ae56a5b87e1a27a71fa39016552b582ce728874608f90765b87e1R578-R583

I don't remember what was the exact issue at the time (something about having non whitespace data before the cell parameters), but feel free to take this change and incorporate it in the lsmo fork!

**Comment by ltalirz** [comment]
ok, thanks!

these changes look oddly specific, and there is a [CSSR file in the repo](https://github.com/lsmo-epfl/zeopp-lsmo/blob/master/tests/EDI.cssr) that we use for CI tests with different amount of whitespace than what I read in your code (which works fine).
I guess in that case we can skip this change - thanks anyhow for the quick reply!
